version: '3.8'

services:
  ocr-app:
    build: .
    container_name: ocr_pipeline
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_models:
